// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoApi.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220628150229_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Coins", b =>
                {
                    b.Property<int>("MonedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("MonedaId");

                    b.ToTable("Conis");

                    b.HasData(
                        new
                        {
                            MonedaId = 1,
                            Descripcion = "Bitcoin",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1386/PNG/512/btc-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95688.png",
                            Valor = 20000.0
                        },
                        new
                        {
                            MonedaId = 2,
                            Descripcion = "Ethereum",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1386/PNG/512/eth-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95753.png",
                            Valor = 1226.0
                        },
                        new
                        {
                            MonedaId = 3,
                            Descripcion = "Litecoin",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1386/PNG/512/ltc-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95811.png",
                            Valor = 56.509999999999998
                        },
                        new
                        {
                            MonedaId = 4,
                            Descripcion = "TRON",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1386/PNG/512/trx-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95619.png",
                            Valor = 0.067979999999999999
                        },
                        new
                        {
                            MonedaId = 5,
                            Descripcion = "Tether",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1386/PNG/512/usdt-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95769.png",
                            Valor = 1.0
                        },
                        new
                        {
                            MonedaId = 6,
                            Descripcion = "BNB",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1385/PNG/512/bnb-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95544.png",
                            Valor = 240.30000000000001
                        },
                        new
                        {
                            MonedaId = 7,
                            Descripcion = "THETA",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1385/PNG/512/theta-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95494.png",
                            Valor = 1.3700000000000001
                        },
                        new
                        {
                            MonedaId = 8,
                            Descripcion = "Degecoin",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1385/PNG/512/doge-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95483.png",
                            Valor = 0.072099999999999997
                        },
                        new
                        {
                            MonedaId = 9,
                            Descripcion = "Cardano",
                            ImageUrl = "https://cdn.icon-icons.com/icons2/1385/PNG/512/ada-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment_95297.png",
                            Valor = 0.5
                        },
                        new
                        {
                            MonedaId = 10,
                            Descripcion = "Solana",
                            ImageUrl = "https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@bea1a9722a8c63169dcc06e86182bf2c55a76bbc/128/black/sol.png",
                            Valor = 39.490000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
